### ISSUE TITLE
segfault on gfortran 5

### ISSUE THREAD

**Issue by floswald** [bast/pfunit-demo#3]
Hi there. 
i'm on fortran 5.2.0 and I get this error. Any idea? has this to do with pfunit itself? thanks!

``````
```fortran
[ 51%] Building Fortran object source/CMakeFiles/pfunit.dir/RobustRunner.F90.o
/Users/florian.oswald/git/pfunit-demo/external/pfunit/source/RobustRunner.F90:148:0:

          testCases = [TestCaseReference(aTest)]
 1
internal compiler error: Segmentation fault: 11

/Users/florian.oswald/git/pfunit-demo/external/pfunit/source/RobustRunner.F90:148:0: internal compiler     error: Abort trap: 6
gfortran: internal compiler error: Abort trap: 6 (program f951)

➜  build git:(master) gfortran --version
GNU Fortran (Homebrew gcc 5.2.0) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.

```
``````

**Comment by bast** [comment]
hi Florian,
I am not able to reproduce this on Arch Linux with GNU 5.2.0.
But what I did now is to update the external/pfunit reference by basically
one year of pFUnit development so hopefully this will fix it. Can you please try?

**Comment by floswald** [comment]
Hi Radovan,

thanks for getting back. That didn't work.

It's strange you don't hit this bug, it's been reported on GCC5.1.0 (
http://sourceforge.net/p/pfunit/bugs/47/). There is also a workaround on
the development branch, see that link. I'm on MacOS with a homebrew GCC. I
tried and this version runs for me, even if the test errors out with

................................................................................

................................................................................

.....................sh: tests/test_xmlprinter_output.tmp: No such file or
directory

At line 124 of file
/Users/florian.oswald/git/pfunit/tests/Test_XmlPrinter.F90 (unit =
538976288, file = 'fort.538976288')

Fortran runtime error: End of file

which is a bit annoying. I would love to have your setup running, the cmake
integration is just what I have been looking for for a long time. thanks
for the good work!

Florian

**Comment by bast** [comment]
Thanks for the feedback. I will look at it. I also try on a Mac. Not sure I will manage before the weekend, though.

**Comment by floswald** [comment]
thats great thanks! I also left a note on the pfunit mailing list, let's
see what comes out.

**Comment by bast** [comment]
My plan is to clean up a bit the CMake code anyway (this was created in a bit of a rush
before a course last year and there are some ugly corners) and also to set up Travis testing on OS X in addition to Linux.

**Comment by floswald** [comment]
brilliant - just what I need.

**Comment by bast** [comment]
So the "good" news is that I can reproduce this problem after adding OS X to the testing:
https://travis-ci.org/bast/pfunit-demo/jobs/83730413#L2394

I am working on a fix.

**Comment by bast** [comment]
For what it's worth switching to the development branch solved it for me ("me" meaning OS X on Travis with gcc 5.2.0):
https://travis-ci.org/bast/pfunit-demo/builds/83734872

The CMake code is still ugly though and I plan to clean it up.

**Comment by floswald** [comment]
Yes same here. I was in contact with Tom at pfunit and he said he'll
release that development branch shortly to the master branch.

**Comment by bast** [comment]
So I can probably consider this issue as closed (from this demo's point of view), right?
I will still tidy up the CMake code on a rainy day.

**Comment by floswald** [comment]
yep, closed. thanks.
