### ISSUE TITLE
How to track down bugs in code when tests are failing?

### ISSUE THREAD

**Issue by leoarnold** [bast/pfunit-demo#4]
Thank you for this outstanding demo of how to use pFUnit which beautifully explains how to integrate pFUnit with a project.

However, suppose I change the subroutine `subtract_numbers` in `hello.f90` to NOT subtract but add the two inputs, then I'll get the test report

```
Running tests...
Test project /home/la/Code/pfunit-demo/build
    Start 1: pftest_alltests
1/1 Test #1: pftest_alltests ..................***Failed    0.03 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.04 sec

The following tests FAILED:
          1 - pftest_alltests (Failed)
Errors while running CTest
make: *** [test] Error 8
```

Is there a way to get more insight into which test failed and why?

**Comment by bast** [comment]
dear Leo,
Thanks! You can get more output either by running the `pftest_alltest` directly
or by exporting `CTEST_OUTPUT_ON_FAILURE=1` telling CMake
to print output on failure, e.g.:

```
$ CTEST_OUTPUT_ON_FAILURE=1 make test
```

I will update the README to reflect this.

**Comment by bast** [comment]
Can I consider this as solved and close the issue?

**Comment by leoarnold** [comment]
Nice, thanks!
